// <auto-generated />
using System;
using CampusConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923085239_AddFacultyAndGrievances")]
    partial class AddFacultyAndGrievances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CampusConnect.Models.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("OrganizerRemarks")
                        .HasColumnType("TEXT")
                        .HasColumnName("organizer_remarks");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("student_id");

                    b.HasKey("ApplicationId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("StudentId");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("CampusConnect.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("department_name");

                    b.HasKey("DepartmentId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("CampusConnect.Models.FacultyOfficeHour", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("slot_id");

                    b.Property<Guid?>("BookedByStudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("booked_by_student_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<Guid>("FacultyUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("faculty_user_id");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_booked");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.HasKey("SlotId");

                    b.HasIndex("BookedByStudentId");

                    b.HasIndex("FacultyUserId");

                    b.ToTable("faculty_office_hours");
                });

            modelBuilder.Entity("CampusConnect.Models.FacultyProfile", b =>
                {
                    b.Property<Guid>("FacultyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("faculty_profile_id");

                    b.Property<string>("CabinNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("cabin_number");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("department_id");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("FacultyProfileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("faculty_profiles");
                });

            modelBuilder.Entity("CampusConnect.Models.Grievance", b =>
                {
                    b.Property<Guid>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("grievance_id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ComplainantUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("complainant_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_anonymous");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sla_due_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrievanceId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ComplainantUserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("grievances");
                });

            modelBuilder.Entity("CampusConnect.Models.GrievanceLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("log_id");

                    b.Property<Guid>("GrievanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("grievance_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_note");

                    b.Property<string>("StatusChangedTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status_changed_to");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("LogId");

                    b.HasIndex("GrievanceId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("grievance_logs");
                });

            modelBuilder.Entity("CampusConnect.Models.Opportunity", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approval_status");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_deadline");

                    b.Property<string>("StipendSalary")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stipend_salary");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_department_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_mode");

                    b.HasKey("OpportunityId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("TargetDepartmentId");

                    b.ToTable("opportunities");
                });

            modelBuilder.Entity("CampusConnect.Models.OpportunitySkill", b =>
                {
                    b.Property<int>("OpportunitySkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("opportunity_skill_id");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.HasKey("OpportunitySkillId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("SkillId");

                    b.ToTable("opportunity_skills");
                });

            modelBuilder.Entity("CampusConnect.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("CampusConnect.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<int>("BatchYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_year");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("department_id");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("github_url");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("linkedin_url");

                    b.Property<int>("ProfileCompletionScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_completion_score");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("resume_url");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("roll_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profiles");
                });

            modelBuilder.Entity("CampusConnect.Models.StudentSkill", b =>
                {
                    b.Property<int>("StudentSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_skill_id");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("proficiency_level");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("student_id");

                    b.HasKey("StudentSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_skills");
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CampusConnect.Models.Application", b =>
                {
                    b.HasOne("CampusConnect.Models.Opportunity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusConnect.Models.FacultyOfficeHour", b =>
                {
                    b.HasOne("CampusConnect.Models.StudentProfile", "BookedByStudent")
                        .WithMany()
                        .HasForeignKey("BookedByStudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusConnect.Models.User", "FacultyUser")
                        .WithMany()
                        .HasForeignKey("FacultyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedByStudent");

                    b.Navigation("FacultyUser");
                });

            modelBuilder.Entity("CampusConnect.Models.FacultyProfile", b =>
                {
                    b.HasOne("CampusConnect.Models.Department", "Department")
                        .WithMany("FacultyProfiles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "User")
                        .WithOne("FacultyProfile")
                        .HasForeignKey("CampusConnect.Models.FacultyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusConnect.Models.Grievance", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusConnect.Models.User", "ComplainantUser")
                        .WithMany()
                        .HasForeignKey("ComplainantUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusConnect.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("ComplainantUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CampusConnect.Models.GrievanceLog", b =>
                {
                    b.HasOne("CampusConnect.Models.Grievance", "Grievance")
                        .WithMany("Logs")
                        .HasForeignKey("GrievanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grievance");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("CampusConnect.Models.Opportunity", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId");

                    b.Navigation("Organizer");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("CampusConnect.Models.OpportunitySkill", b =>
                {
                    b.HasOne("CampusConnect.Models.Opportunity", "Opportunity")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CampusConnect.Models.StudentProfile", b =>
                {
                    b.HasOne("CampusConnect.Models.Department", "Department")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("CampusConnect.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusConnect.Models.StudentSkill", b =>
                {
                    b.HasOne("CampusConnect.Models.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.StudentProfile", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CampusConnect.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CampusConnect.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CampusConnect.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampusConnect.Models.Department", b =>
                {
                    b.Navigation("FacultyProfiles");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("CampusConnect.Models.Grievance", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CampusConnect.Models.Opportunity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("CampusConnect.Models.Skill", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("CampusConnect.Models.StudentProfile", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Navigation("FacultyProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
